<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>intasaumo - Admin login</title>
</head>
<body>
    <div class="content admin--login">
        <h1>Login to admin panel</h1>
        <form method="POST" action="<?= "/admin/login" ?>">
            <div class="form-group">
                <div class="form-input">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username">
                </div>
                <div class="form-input">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password">
                </div>
                <button type="submit">Send</button>
            </div>
        </form>
    </div>
</body>
</html>