<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>intasaumo - Admin login</title>
</head>
<body>
<div>
    <h1>Rénitialisation du mot de passe</h1>
    <p>Veuillez renseigner le mail associé à votre compte, un email va vous être envoyer avec les instructions vous permettant de réinitialiser votre mot de passe :</p>
    <?php echo $userLostPassword; ?>
</div>
</body>
</html>