<div>
    <h1>Rénitialisation du mot de passe</h1>
    <p>Veuillez renseigner le mail associé à votre compte, un email va vous être envoyer avec les instructions vous permettant de réinitialiser votre mot de passe :</p>
    <?php echo $userLostPassword; ?>
    <small style="color: red">Nous n’avons pas trouvé de compte correspondant à cette adresse mail.</small>
    <br>
    <small style="color: red">Veuillez essayer une autre adresse e-mail.</small>
</div>