<div>
    <h1>Réinitialisation du mot de passe</h1>
    <p>Veuillez renseigner le mail associé à votre compte, un email va vous être envoyer avec les instructions vous permettant de réinitialiser votre mot de passe :</p>
    <?php if(isset($errors) && !empty($errors)): ?>
        <ul>
            <?php foreach($errors as $error): ?>
                <li><?php echo $error;?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php echo $userLostPassword; ?>
    <?php if(($message = $helper->getFlashMessage('resetEmailSend'))):?>
        <p><?php echo $message;?></p>
    <?php elseif(($message = $helper->getFlashMessage('noAccountFound'))):?>
        <p> <?php echo $message;?></p>
    <?php elseif(($message = $helper->getFlashMessage('postError'))):?>
        <p> <?php echo $message;?></p>
    <?php elseif(($message = $helper->getFlashMessage('linkExpired'))):?>
        <p> <?php echo $message;?></p>
    <?php elseif(($message = $helper->getFlashMessage('errorReset'))):?>
        <p> <?php echo $message;?></p>
    <?php endif;?>
</div>