<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>intasaumo - Admin login</title>
</head>
<body>
    <div class="content admin--login">
        <h1>Rénitialisation du mot de passe</h1>
        <?php echo $userResetPassword; ?>
    </div>
</body>
</html>