<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>intasaumo - Admin login</title>
</head>
<body>
    <div class="content admin--login">
        <h1>Réinitialisation du mot de passe</h1>
        <?php if(isset($errors) && !empty($errors)): ?>
            <ul>
                <?php foreach($errors as $error): ?>
                    <li><?php echo $error;?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?php echo $userResetPassword; ?>
    </div>
</body>
</html>