<?php include "/layouts/header.phtml"?>

    <div class="content email-userRegister">
        <p>Nous avons reçu une demande de réinitialisation de votre mot de passe GoSchool. Veuillez cliquer sur le lien ci-dessous pour réinitialiser votre mot de passe.</p>
        <p>Si la demande ne vient pas de vous, veuillez ignorer cet email.</p>
        <p>Voici votre lien de réinitialisation du mot de passe : </p>
    </div>

<?php include "/layouts/footer.phtml"?><?php
