<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin</title>
    <link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
<nav class="admin-main--menu"></nav>
<header class="admin-main--header"><h2>Header</h2></header>

<div class="admin-main--content">
    {{content}}
</div>

<footer class="admin-main--footer"><h2>Footer</h2></footer>
</body>
</html>